# Generated by Django 5.0.8 on 2025-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
    ]
