# Generated by Django 5.1.6 on 2025-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
