# Generated by Django 5.1.6 on 2025-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
    ]
