# Generated by Django 5.0.8 on 2025-02-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_menuitems_options'),
        ('menu', '0007_alter_menuitems_image'),
    ]

    operations = [
    ]
