# Generated by Django 5.1.6 on 2025-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_merge_20250227_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
