# Generated by Django 5.1.6 on 2025-02-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_merge_20250227_0731'),
        ('menu', '0009_alter_menuitems_image'),
    ]

    operations = [
    ]
