# Generated by Django 5.0.8 on 2025-02-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('current_order', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('empty', 'empty'), ('fill', 'fill')], default='empty', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('cooking', 'cooking'), ('served', 'served')], default='ongoing', max_length=100)),
                ('timestamp', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.tables')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Reciepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100)),
                ('timestamp', models.TimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
