# Generated by Django 5.0.8 on 2025-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_options_alter_ordersdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
