# Generated by Django 5.1.6 on 2025-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_tables_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reciepts',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
