# Generated by Django 5.0.8 on 2025-02-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
