# Generated by Django 5.1.6 on 2025-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customers_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='admin', max_length=10),
        ),
    ]
