# Generated by Django 5.0.8 on 2025-02-12 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Hot Drinks', 'Hot Drinks'), ('Cold Drinks', 'Cold Drinks'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner')], max_length=20)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('serving_time_period', models.PositiveIntegerField()),
                ('estimated_cooking_time', models.PositiveIntegerField()),
            ],
        ),
    ]
